// _createart generated by momo5502.  modify at your own risk. Changing values should be fine.
main()
{

	level.tweakfile = true;
	
	setDevDvar( "scr_fog_disable", "0" );

	setExpFog( 300, 4000, 0.5, 0.5, 0.5, 1, 0 );
		
	VisionSetNaked( "co_hunted", 0 );
		
	setdvar( "r_specularcolorscale", "5" );
}
